theme = "autumn"

[editor]
line-number = "relative"
mouse = false
auto-pairs = false
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.file-picker]
hidden = false # Don't ignore hidden files
git-ignore = false # Don't read gitignore files
ignore = false # Don't read .ignore files

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "file-encoding", "file-type", "position-percentage"]
separator = "│"
